apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: decapod-controller
  namespace: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argo
    server: https://kubernetes.default.svc
  - namespace: decapod-db
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
